import { computed } from 'vue';
import { i18n } from 'boot/i18n'
const { t } = i18n.global

export const empRecordColumns = computed(() => {
  return [
    {
      name: 'fullTime',
      required: true,
      label: t('client.backOrder.fullTime'),
      align: 'center',
      field: 'fullTime',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'partTimeJob',
      required: true,
      label: t('client.variousAchievement.partTimeJob'),
      align: 'center',
      field: 'partTimeJob',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'dispatch',
      required: true,
      label: t('client.backOrder.dispatch'),
      align: 'center',
      field: 'dispatch',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'TemptoPerm',
      required: true,
      label: t('client.variousAchievement.temptoperm'),
      align: 'center',
      field: 'TemptoPerm',
      classes: 'bg-white',
      sortable: false,
    },
  ]
});

export const dispatchColumns = computed(() => {
  return [
    {
      name: 'inHouseBO',
      required: true,
      label: t('client.variousAchievement.inHouseBO'),
      align: 'center',
      field: 'inHouseBO',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'inHouseFIX',
      required: true,
      label: t('client.variousAchievement.inHouseFIX'),
      align: 'center',
      field: 'inHouseFIX',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'companyJob',
      required: true,
      label: t('client.variousAchievement.companyJob'),
      align: 'center',
      field: 'companyJob',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'inHouseOffer',
      required: true,
      label: t('client.variousAchievement.inHouseOffer'),
      align: 'center',
      field: 'inHouseOffer',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'inHouseEmployment',
      required: true,
      label: t('client.variousAchievement.inHouseEmployment'),
      align: 'center',
      field: 'inHouseEmployment',
      classes: 'bg-white',
      sortable: false,
    },
    {
      name: 'otherCompanyBO',
      required: true,
      label: t('client.variousAchievement.otherCompanyBO'),
      align: 'center',
      field: 'otherCompanyBO',
      sortable: false,
      headerClasses: 'bg-yellow-4',
      classes: 'bg-yellow-4 ellipsis',
    },
    {
      name: 'competitorFIX',
      required: true,
      label: t('client.variousAchievement.competitorFIX'),
      align: 'center',
      field: 'competitorFIX',
      sortable: false,
      headerClasses: 'bg-yellow-4',
      classes: 'bg-yellow-4 ellipsis',
    },
    {
      name: 'otherCompanyJob',
      required: true,
      label: t('client.variousAchievement.otherCompanyJob'),
      align: 'center',
      field: 'otherCompanyJob',
      sortable: false,
      headerClasses: 'bg-yellow-4',
      classes: 'bg-yellow-4 ellipsis',
    },
    {
      name: 'otherCompany',
      required: true,
      label: t('client.variousAchievement.otherCompany'),
      align: 'center',
      field: 'otherCompany',
      sortable: false,
      headerClasses: 'bg-yellow-4',
      classes: 'bg-yellow-4 ellipsis',
    },
    {
      name: 'joiningAnotherCompany',
      required: true,
      label: t('client.variousAchievement.joiningAnotherCompany'),
      align: 'center',
      field: 'joiningAnotherCompany',
      sortable: false,
      headerClasses: 'bg-yellow-4',
      classes: 'bg-yellow-4 ellipsis',
    },
  ];
});
