export type graphType = 'BasedOnLeftMostItemDate'|'BasedOnEachItemDate'
export type typeOfQuery =
  | 'applicants'
  | 'validApplicants'
  | 'contactApplicants'
  | 'attractionApplicants'
  | 'attendApplicants'
  | 'fix'
  | 'inspection'
  | 'offer'
  | 'admission'
  | 'BO'
  | 'BOIsfirst'
  | 'BOIsnotfirst'
  | 'generalDispatch'
  | 'introduction'
  | 'TTP'
  | 'nurse'
  | 'nursingCare';
